### ISSUE TITLE
what about proxy?

### ISSUE THREAD

**Issue by roysG** [behdadahmadi/instamaker#2]

**Comment by behdadahmadi** [comment]
It doesn't work anymore due to Instagram changed it's API one year ago.

**Comment by virginsince1997** [comment]
The program still works ,It still works , please add proxy

**Comment by behdadahmadi** [comment]
@virginsince1997 I didn't check the script since some month ago,I didn't know it works. I will add proxy option to the script.

**Comment by virginsince1997** [comment]
Thanks ,I use it alot , works really well, please implement it asap , thank
you in advance ..your work is appreciated

**Comment by behdadahmadi** [comment]
You're welcome. I'm so glad you use it and like it. I will implement it so soon. Thank you for your kind words.

**Comment by virginsince1997** [comment]
You're welcome bro

**Comment by rektbyme** [comment]
im trying to implement a proxy option, give me 3 more hours and ill have it :dancing_men:

**Comment by virginsince1997** [comment]
Alright thank you

**Comment by virginsince1997** [comment]
@rektbyme  still waiting on you bro

**Comment by virginsince1997** [comment]
@behdadahmadi still waiting on you bro

**Comment by behdadahmadi** [comment]
@virginsince1997 Which OS do you use bro? If you are using macOS or Linux, you can just simply set the environment variables : HTTP_PROXY and HTTPS_PROXY .
`export HTTP_PROXY="http://10.10.1.10:3128"`
`export HTTPS_PROXY="http://10.10.1.10:1080"`
For example, I set 2 Proxies (one for HTTP,and another one for HTTPS). Just change the address of your desired proxies. It will be like this:
`export HTTP_PROXY="http://YOUR_HTTP_PROXY_ADDRESS:PORT"`
`export HTTPS_PROXY="http://YOUR_HTTPS_PROXY_ADDRESS:PORT"`
By the way,I will add proxy option to the script,these days I am so busy bro.

**Comment by virginsince1997** [comment]
I run the script on my phone with termux

**Comment by behdadahmadi** [comment]
@virginsince1997 Aha OK bro. Do you use on proxy address for both HTTP and HTTPS?

**Comment by virginsince1997** [comment]
No I don't I just run script

**Comment by virginsince1997** [comment]
@behdadahmadi didn't work, checked if the IP has changed with ,,,
wget -q -O - checkip.dyndns.org \
| sed -e 's/.*Current IP Address: //' -e 's/<.*$//' still the same

**Comment by virginsince1997** [comment]
'''
#!/usr/bin/python
#Instagram Account Maker
#by Behdad Ahmadi
#Twitter: behdadahmadi
#https://github.com/behdadahmadi
#https://logicalcoders.com


import requests
import hmac
import hashlib
import random
import string
import json
import argparse
import os

proxy = 'http://192.99.68.187:8080'

os.environ['http_proxy'] = proxy 
os.environ['HTTP_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTPS_PROXY'] = proxy







def HMAC(text):
    key = '3f0a7d75e094c7385e3dbaa026877f2e067cbd1a4dbcf3867748f6b26f257117'
    hash = hmac.new(key,msg=text,digestmod=hashlib.sha256)
    return hash.hexdigest()

def randomString(size):
    chars = string.ascii_lowercase + string.digits
    return ''.join(random.choice(chars) for _ in range(size))

def banner():
    dotname = "-" * 31
    print " "
    print dotname.center(16,'-')
    print ".:: " + 'Instagram Account Maker' + " ::.".center(4)
    print "by Behdad Ahmadi".center(30)
    print "Twitter:behdadahmadi".center(30)
    print dotname.center(20,'-')



def main():
    banner()
    parser = argparse.ArgumentParser()
    parser.add_argument('name', help='Full Name')
    parser.add_argument('username', help='Username')
    parser.add_argument('email', help='Email')
    parser.add_argument('password', help='Password')
    args = parser.parse_args()

    getHeaders = {'User-Agent':'Instagram 7.1.1 Android (21/5.0.2; 480dpi; 1080x1776; LGE/Google; Nexus 5; hammerhead; hammerhead; en_US)',
               'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
               'Accept-Encoding':'gzip, deflate, sdch',
               'Accept-Language':'en-US,en;q=0.8',
               'upgrade-insecure-requests':'1'}

    s = requests.Session()
    s.get('https://instagram.com',headers=getHeaders)
    guid = randomString(8) + '-' + randomString(4) + "-" + randomString(4) + '-' + randomString(4) + '-' +randomString(12)
    device_id = 'android-' + str(HMAC(str(random.randint(1000,9999))))[0:min(64,16)]
    information = {'username':args.username,'first_name':args.name,'password':args.password,'email':args.email,'device_id':device_id,'guid':guid}
    js = json.dumps(information)
    payload = {'signed_body': HMAC(js) + '.' + js,'ig_sig_key_version':'4'}
    postHeaders = {'Host':'i.instagram.com',
                  'User-Agent':'Instagram 7.1.1 Android (21/5.0.2; 480dpi; 1080x1776; LGE/Google; Nexus 5; hammerhead; hammerhead; en_US)',
                  'Accept-Language':'en-US',
                  'Accept-Encoding':'gzip',
                  'Cookie2':'$Version=1',
                  'X-IG-Connection-Type':'WIFI',
                  'X-IG-Capabilities':'BQ=='
                  }
    x = s.post('https://i.instagram.com/api/v1/accounts/create/',headers=postHeaders,data=payload)
    result = json.loads(x.content)
    if result['status'] != 'fail':
        if result['account_created'] == True:
            print 'Account has been created successfully'
        else:
            print 'Error:'
            for i in result['errors']:
                print str(result['errors'][i][0])
    else:
        if result['spam'] == True:
            print 'Instagram blocks your IP due to spamming behaviour.'


if __name__ == '__main__':
    main()
'''

**Comment by behdadahmadi** [comment]
Is  'http://192.99.68.187:8080' the proxy which you want to use?

**Comment by virginsince1997** [comment]
Yes

**Comment by virginsince1997** [comment]
Help me out bro

**Comment by behdadahmadi** [comment]
@virginsince1997 Bro,I added a file named "instaMakerWithProxies.py" for you in the new branch called "withProxy". Just run the script it gonna work.

**Comment by virginsince1997** [comment]
I got this error whole running "instamakerwithproxies.py" script 

-------------------------------
Traceback (most recent call last):
  File "instaMakerWithProxies.py", line 87, in <module>
    main()
  File "instaMakerWithProxies.py", line 57, in main
    s = requests.Session(proxies=proxies)
TypeError: __init__() got an unexpected keyword argument 'proxies'
$

**Comment by virginsince1997** [comment]
![screenshot_20171003-133909](https://user-images.githubusercontent.com/21218962/31125469-4b6e0060-a840-11e7-89e9-4efdfff67e85.png)

**Comment by behdadahmadi** [comment]
Let me check and rewrite the script

**Comment by behdadahmadi** [comment]
@virginsince1997 Now please check the file. I edited. It should work OK right now.

**Comment by virginsince1997** [comment]
Thank you I appreciate it

**Comment by behdadahmadi** [comment]
@virginsince1997 You're welcome. I'm so happy it works and helps you.

**Comment by yray** [comment]
@behdadahmadi 

I always get error
"This username isn't available. Please try again."

I have tried to another usernames, and it always giving me this error.
Can you help me?

**Comment by virginsince1997** [comment]
all the proxy I use don't work , always getting "banned by Instagram " even
at first try

**Comment by yray** [comment]
@virginsince1997 

I do get that error "Instagram blocks your IP due to spamming behaviour."
And my solution is, try running the script again, and it will get thru you somehow.

**Comment by virginsince1997** [comment]
Didn't work for me , where do you run your script

**Comment by yray** [comment]
@virginsince1997 

On ubuntu server

**Comment by behdadahmadi** [comment]
@yray I think the username you want to create is used by someone else. Make sure about it by using Instagram app and attempt to create the user via desired username (the one which you try to create). This is from Instagram API ,and I can't help.

**Comment by behdadahmadi** [comment]
@virginsince1997 Maybe you are using public HTTP proxies. Instagram block them due to many requests from same IP address.

**Comment by yray** [comment]
@behdadahmadi 

Tried using 50 different combination of usernames, passwords, emails. And still no luck at all.
But when I tried to register manually via browser using one of my usernames, it can register flawlessly.

I doubt it's from IG itself :(

**Comment by virginsince1997** [comment]
Try to see if you input the arguments correctly

**Comment by rektbyme** [comment]
@behdadahmadi we can establish a range for the characters of the password and username maybe between 10-15 characters, so the prob of getting the error existent username is minimum, about the proxy checkout using controlport of tor (9051 or 9151 default control port in tor), usefull as hell app for changing ip in each request :)

**Comment by behdadahmadi** [comment]
@rektbyme Yes man! That's awesome! It gonna be automatic Instagram account creator!

**Comment by virginsince1997** [comment]
How do I use tor proxy for it ,,,all the proxies I use keep failing on 3rd
try

**Comment by behdadahmadi** [comment]
@virginsince1997 I don't have any idea. I never use Tor proxy for the scripts. But maybe until next week I commit new script to work with Tor proxy. I'm sorry, I am so busy these days.

**Comment by Lounah** [comment]
hi can u please tell me how many requests does it require to get banned by ip?

**Comment by behdadahmadi** [comment]
@Lounah Hi, I think 3 requests per minutes could lead to be banned by IP.

**Comment by virginsince1997** [comment]
Still waiting for your implementation😿

**Comment by behdadahmadi** [comment]
@virginsince1997 Really? :-D , honestly I am working on an app which is for Android and iOS. It really makes me upset and time consuming. I will implement Tor proxy option for 3,4 days later. Thank you.

**Comment by annaT1970** [comment]
@behdadahmadi Hi there.as far as I see this won't work anymore! right? whats the reason?

**Comment by behdadahmadi** [comment]
@annaT1970 Hi, Yes. The script does not work anymore due to Instagram API changes. If I find a solution,I will change the script to work.
